### PR TITLE
Fixes #222: "Make flathead too big for phillips screws"

### LINKED ISSUE #222: make flathead too big for phillips head screws

### PR DESCRIPTION
**Pull request by libraun**
* Added check to prevent player from trying to unscrew Ellie's computer with a flathead screwdriver (in which case it prints a minor hint and returns false); 
* Adjusted header test '_ready coffee card' to also pick up flathead screwdriver, to test unscrewing ellie's computer; 
* Added tests where the player attempts to unlock ellie's computer using both the flathead screwdriver and the phillips head screwdriver, using various acceptable phrases.

### CODE REVIEW

**Comment by pahp** [comment]
Here's a transcript of me trying:

```
> open ellie's computer with flathead
You try to unscrew the screws with your flathead screwdriver, but it does not fit.You can't
unlock that.

> unlock ellie's computer with flathead
You try to unscrew the screws with your flathead screwdriver, but it does not fit.You can't
unlock that.

> unlock computer with flathead
You try to unscrew the screws with your flathead screwdriver, but it does not fit.You can't
unlock that.

> 
```

I think it would be better if it said something like:

"... it does not fit because the screws are Phillips head screws."

Can we suppress the "You can't unlock that." message? If so, please do.

If it must be there, it should have a space after the period.

**Review by pahp — CHANGES_REQUESTED** [review]
See comments here: https://github.com/UMDLARS/one_night_in_sf/pull/265#issuecomment-2369361581

**Comment by pahp** [comment]
Hey @libraun or @spacehobo -- can you give this a peek? You'll need to resolve the conflict for the new strings about Ellie's computer. (I have removed 'return false' per Spacehobo's suggestion.)

**Comment by libraun** [comment]
Yes!

**Pull request merged**
