### PR TITLE
Use

### PR DESCRIPTION
**Pull request by spacehobo**

### CODE REVIEW

**Comment by spacehobo** [comment]
This PR is kind of a mix of things, soz.

I turned the `use` verb into a `HelpOn` action that either tells you the object is interesting to look at or read, but probably doesn't *do* anything, and then added `instructions` to the three objects that reacted to the `use` verb already.

I also added a test case for one of the easter eggs, partly because I was debugging another thing and wanted to rule out the test harness's misbehaviour in the face of formatted text.

And yeah, there's a bugfix buried in here that should probably be its own commit straight to main, but while I'm here...

**Comment by pahp** [comment]
I've been trying to put witty comments into the merge message, but I don't know if those are showing up anywhere. Oh well.

**Comment by spacehobo** [comment]
> I've been trying to put witty comments into the merge message, but I don't know if those are showing up anywhere. Oh well.

I think they show up [in the git log itself](https://github.com/UMDLARS/one_night_in_sf/commit/127768cc9ffe765711f7e30fc78e3279be389579).
image

**Comment by pahp** [comment]
Ah, thanks!

**Pull request merged**
